"""Building something to compare a portfolio against.

**What this is not.** GitHub has no public "trending" API. The page at
github.com/trending is generated by an internal service with no documented
endpoint, and scraping it would make Scout depend on somebody's HTML.

So the comparison corpus is built from the Search API: for each topic the user
already works near, ask for well-starred repositories pushed recently. That is a
*heuristic for what is active and visible in a field*, and it is not the same
thing as what is trending, what is good, or what employers value. The plan calls
for saying so plainly rather than dressing it up, and the report says it too -
in the output, not only in this docstring, because the person reading a ranked
list is the one who needs to know how it was made.

Two biases are worth naming because they change how the output should be read:

**Stars measure attention, not quality.** A tutorial repository outstars most
production code. The floor exists to filter abandoned experiments, not to rank.

**Search returns what matches the query.** Seeding the query from the user's own
topics means the corpus is drawn from their neighbourhood, so the gaps found are
"things adjacent to what you do" rather than "things you should do". That is the
useful question, but it is a narrower one than it looks.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

from .github import GitHubClient, Repo

MIN_STARS = 200
"""Low enough to include serious niche work, high enough to exclude the long
tail of unfinished weekend projects."""

ACTIVE_WITHIN_DAYS = 365
"""A repository nobody has pushed to in a year is not a signal about what is
current, whatever its star count."""

MAX_TOPICS = 6
"""Each topic costs one search request, and the budget is 60 an hour
unauthenticated."""

REPOS_PER_TOPIC = 12

#: Topics too broad to say anything. A corpus seeded on "python" is a corpus of
#: everything, and every portfolio has a gap against everything.
GENERIC_TOPICS = frozenset(
    {
        "python", "javascript", "typescript", "java", "go", "golang", "rust",
        "c", "cpp", "c-plus-plus", "csharp", "ruby", "php", "swift", "kotlin",
        "html", "css", "shell", "bash", "code", "programming", "software",
        "library", "framework", "tool", "tools", "app", "application",
        "project", "example", "demo", "test", "hacktoberfest", "awesome",
        "open-source", "opensource", "github", "learning", "tutorial",
    }
)


@dataclass(frozen=True, slots=True)
class Seed:
    """One search to run, and which GitHub qualifier it uses.

    Topics and languages are not interchangeable, which the first version of
    this module missed. ``topic:python`` is a corpus of everything, so
    ``python`` belongs in :data:`GENERIC_TOPICS` - but a portfolio with no
    topics at all still has languages, and filtering those out with the same
    list left nothing to search on. ``language:Python`` is a different query:
    "active, well-starred Python work" is a narrower and perfectly reasonable
    comparison set.
    """

    value: str
    kind: str = "topic"

    def __str__(self) -> str:
        return f"{self.kind}:{self.value}"


@dataclass(frozen=True, slots=True)
class Corpus:
    """Comparison repositories, and an account of how they were chosen."""

    repos: tuple[Repo, ...]
    topics: tuple[str, ...]
    query_notes: tuple[str, ...]
    min_stars: int = MIN_STARS

    def __len__(self) -> int:
        return len(self.repos)

    @property
    def provenance(self) -> str:
        """One line saying what this is, for the top of the report."""
        return (
            f"{len(self.repos)} repositories with >{self.min_stars} stars, pushed in the "
            f"last {ACTIVE_WITHIN_DAYS // 30} months, found by searching "
            f"{', '.join(self.topics) or 'nothing'}. "
            "GitHub has no trending API - this is a heuristic for what is active "
            "and visible, not a ranking of what is good."
        )


def seed_topics(repos: list[Repo], *, limit: int = MAX_TOPICS) -> list[Seed]:
    """What to search, drawn from the user's own repositories.

    Topics first, because they are what the author chose to say the project is
    about. Languages fill whatever is left over, since plenty of perfectly good
    repositories carry no topics at all - and a portfolio Scout cannot seed
    from is a portfolio Scout cannot say anything about.
    """
    topics: Counter[str] = Counter()
    for repo in repos:
        for topic in repo.topics:
            cleaned = topic.strip().lower()
            if cleaned and cleaned not in GENERIC_TOPICS:
                topics[cleaned] += 1

    seeds = [Seed(value, "topic") for value, _ in topics.most_common(limit)]
    if len(seeds) >= limit:
        return seeds

    languages: Counter[str] = Counter()
    for repo in repos:
        language = repo.language.strip()
        if language:
            languages[language] += 1
    for value, _ in languages.most_common(limit - len(seeds)):
        seeds.append(Seed(value, "language"))
    return seeds


def build_query(
    seed: Seed | str, *, min_stars: int = MIN_STARS, days: int = ACTIVE_WITHIN_DAYS
) -> str:
    """The Search API query for one seed."""
    if isinstance(seed, str):
        seed = Seed(seed, "topic")
    since = (datetime.now(UTC) - timedelta(days=days)).date().isoformat()
    return f"{seed.kind}:{seed.value} stars:>{min_stars} pushed:>{since}"


def build_corpus(
    client: GitHubClient,
    user_repos: list[Repo],
    *,
    max_topics: int = MAX_TOPICS,
    per_topic: int = REPOS_PER_TOPIC,
    min_stars: int = MIN_STARS,
) -> Corpus:
    """Search each seed topic and collect the results, deduplicated.

    Stops early and reports it rather than failing when the request budget runs
    out: a corpus of four topics with the other two named is more useful than an
    exception, as long as the report says which is which.
    """
    seeds = seed_topics(user_repos, limit=max_topics)
    if not seeds:
        return Corpus((), (), ("your repositories carry no topics or languages to search on",))

    owned = {repo.full_name.lower() for repo in user_repos}
    seen: set[str] = set()
    collected: list[Repo] = []
    notes: list[str] = []
    searched: list[str] = []

    for seed in seeds:
        if not client.can_spend(1):
            unsearched = ", ".join(str(s) for s in seeds[len(searched) :])
            notes.append(f"stopped early: no request budget left for {unsearched}")
            break
        query = build_query(seed, min_stars=min_stars)
        try:
            found = client.search_repos(query, limit=per_topic)
        except Exception as exc:  # noqa: BLE001 - one bad seed must not end the run
            notes.append(f"{seed}: search failed ({type(exc).__name__})")
            continue

        searched.append(str(seed))
        for repo in found:
            key = repo.full_name.lower()
            # The user's own repositories cannot be evidence of a gap in the
            # user's own portfolio.
            if key in owned or key in seen:
                continue
            seen.add(key)
            collected.append(repo)

    return Corpus(
        repos=tuple(collected),
        topics=tuple(searched),
        query_notes=tuple(notes),
        min_stars=min_stars,
    )
